#include "home_panel.h"
#include "feature_manager.h"
#include "macro_engine.h"
#include "instant_sniper.h"
#include "aim_controller.h"
namespace d3dref9 {
HomePanel& HomePanel::Instance(){static HomePanel p;return p;}
bool HomePanel::Create(HINSTANCE h){inst_=h;WNDCLASSW wc{};wc.lpfnWndProc=WndProc;wc.hInstance=h;wc.lpszClassName=L"d3dref9_autonomous_panel";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassW(&wc);hwnd_=CreateWindowExW(WS_EX_TOPMOST|WS_EX_TOOLWINDOW|WS_EX_LAYERED,L"d3dref9_autonomous_panel",L"d3dref9自治",WS_POPUP,8,8,340,560,nullptr,nullptr,h,this);if(!hwnd_)return false;SetLayeredWindowAttributes(hwnd_,0,140,LWA_ALPHA);ShowWindow(hwnd_,SW_HIDE);SetTimer(hwnd_,1,100,nullptr);return true;}
void HomePanel::Destroy(){if(hwnd_){KillTimer(hwnd_,1);DestroyWindow(hwnd_);hwnd_=nullptr;}}
void HomePanel::Toggle(){if(!hwnd_)return;bool v=!visible_.load();visible_=v;ShowWindow(hwnd_,v?SW_SHOW:SW_HIDE);}
LRESULT CALLBACK HomePanel::WndProc(HWND w,UINT m,WPARAM wp,LPARAM lp){HomePanel*p=(HomePanel*)GetWindowLongPtrW(w,GWLP_USERDATA);if(m==WM_NCCREATE){p=(HomePanel*)((CREATESTRUCTW*)lp)->lpCreateParams;SetWindowLongPtrW(w,GWLP_USERDATA,(LONG_PTR)p);}return p?p->Handle(w,m,wp,lp):DefWindowProcW(w,m,wp,lp);}
LRESULT HomePanel::Handle(HWND w,UINT m,WPARAM wp,LPARAM lp){switch(m){case WM_PAINT:{PAINTSTRUCT ps;HDC dc=BeginPaint(w,&ps);Paint(dc);EndPaint(w,&ps);return 0;}case WM_TIMER:InvalidateRect(w,nullptr,FALSE);return 0;case WM_LBUTTONDOWN:{int row=GET_Y_LPARAM(lp);constexpr size_t n=(size_t)Feature::Count;if(row>=38&&row<38+(int)n*28)Features().Toggle((Feature)((row-38)/28));else if(row>=38+((int)n+2)*28&&row<38+((int)n+3)*28)MacroEngine::Instance().Toggle();else if(row>=38+((int)n+6)*28)MacroEngine::Instance().EmergencyStop();return 0;}case WM_CLOSE:visible_=false;ShowWindow(w,SW_HIDE);return 0;}return DefWindowProcW(w,m,wp,lp);}
void HomePanel::Paint(HDC dc){RECT r;GetClientRect(hwnd_,&r);HBRUSH bg=CreateSolidBrush(RGB(25,25,30));FillRect(dc,&r,bg);DeleteObject(bg);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(230,230,230));HFONT f=CreateFontW(16,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,0,0,L"Microsoft YaHei");HFONT old=(HFONT)SelectObject(dc,f);TextOutW(dc,12,10,L"d3dref9自治  Home 面板",22);auto rows=Features().PanelSnapshot();int y=38;for(auto&x:rows){std::wstring s=x.first+L"  ["+(x.second?L"开":L"关")+L"]";TextOutW(dc,12,y,s.c_str(),(int)s.size());y+=28;}std::wstring mode=L"开枪模式: "+std::wstring(InstantSniper::Instance().SniperMode()?L"瞬狙":L"普通");TextOutW(dc,12,y,mode.c_str(),(int)mode.size());y+=28;if(!InstantSniper::Instance().SniperMode()){std::wstring bone=L"普通瞄准位置: "+std::wstring(AimController::Instance().NormalLabel())+L"（P切换）";TextOutW(dc,12,y,bone.c_str(),(int)bone.size());y+=28;}else{TextOutW(dc,12,y,L"瞬狙瞄准: 自动选择准心最近部位",28);y+=28;}std::wstring m=L"键盘宏  ["+(MacroEngine::Instance().Enabled()?L"开":L"关")+L"]";TextOutW(dc,12,y,m.c_str(),(int)m.size());y+=28;std::wstring st=L"宏状态: "+(MacroEngine::Instance().Running()?L"运行中":L"空闲");TextOutW(dc,12,y,st.c_str(),(int)st.size());y+=28;std::wstring cool=L"瞬狙冷却: "+std::to_wstring(InstantSniper::Instance().CooldownLeft())+L" ms";TextOutW(dc,12,y,cool.c_str(),(int)cool.size());y+=28;TextOutW(dc,12,y,L"宏急停（点击立即停止）",22);SelectObject(dc,old);DeleteObject(f);}
}
