#include "macro_engine.h"
#include "input_router.h"
namespace d3dref9 {
namespace {constexpr WORD W=0x011,S=0x01F,A=0x01E,D=0x020,SP=0x039,CTRL=0x01D,SHIFT=0x02A;}
MacroEngine& MacroEngine::Instance(){static MacroEngine m;return m;}
void MacroEngine::Start(){enabled_=true;emergency_=false;}
void MacroEngine::Stop(){enabled_=false;emergency_=true;generation_++;action_=0;running_=false;InputRouter::Instance().ReleaseOwned(InputOwner::Macro);}
void MacroEngine::Toggle(){if(enabled_)Stop();else Start();}
void MacroEngine::EmergencyStop(){emergency_=true;generation_++;action_=0;running_=false;InputRouter::Instance().ReleaseOwned(InputOwner::Macro);}
bool MacroEngine::Begin(uint32_t a){if(!enabled_||emergency_||running_)return false;running_=true;action_=a;count_=0;return true;}
bool MacroEngine::Alive(uint32_t a,uint64_t g)const{return enabled_&&!emergency_&&running_&&action_==a&&generation_==g;}
void MacroEngine::End(uint32_t a){if(action_==a){InputRouter::Instance().ReleaseOwned(InputOwner::Macro);action_=0;running_=false;}}
void MacroEngine::Launch(uint32_t a,void(MacroEngine::*fn)(uint32_t,uint64_t)){if(!Begin(a))return;auto g=generation_.load();std::thread([this,a,g,fn]{(this->*fn)(a,g);End(a);}).detach();}
void MacroEngine::OnKey(DWORD vk,bool d){if(vk<down_.size()){std::lock_guard<std::mutex>l(keyMu_);down_[vk]=d;}auto p=[this](DWORD k){return InputRouter::Instance().Physical(k);};
 if(vk=='O'&&d){Toggle();return;} if(!enabled_||emergency_)return;
 if(!d){ if(vk==VK_LCONTROL&&p('W')) Launch(1,&MacroEngine::LCtrl); return; }
 if(vk=='F'&&p('W'))Launch(2,&MacroEngine::WF); else if(vk=='C'&&p('W'))Launch(3,&MacroEngine::WC); else if(vk==VK_LMENU&&p('W'))Launch(4,&MacroEngine::WLAlt); else if(vk=='F'&&p('S'))Launch(5,&MacroEngine::SF); else if(vk=='C'&&p('S'))Launch(6,&MacroEngine::SC); else if(vk==VK_LMENU&&p('S'))Launch(7,&MacroEngine::SLAlt); else if(vk=='X'&&p('Z'))Launch(8,&MacroEngine::ZX); else if(vk=='C'&&p('Z'))Launch(9,&MacroEngine::ZC); else if(vk==VK_OEM_COMMA||vk==VK_OEM_102)Launch(10,&MacroEngine::TurnLeft); else if(vk==VK_OEM_PERIOD)Launch(11,&MacroEngine::TurnRight); }
void MacroEngine::LCtrl(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();SleepMs(100);if(!Alive(a,g))return;if(!r.Physical(VK_LSHIFT))r.KeyScan(SHIFT,true,InputOwner::Macro);SleepMs(50);if(!r.Physical(VK_LSHIFT))r.KeyScan(SHIFT,false,InputOwner::Macro);SleepMs(50);if(!r.Physical(VK_LCONTROL))r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(50);if(!r.Physical(VK_LCONTROL))r.KeyScan(CTRL,false,InputOwner::Macro);SleepMs(50);if(!r.Physical(VK_LSHIFT))r.KeyScan(SHIFT,true,InputOwner::Macro);SleepMs(50);r.KeyScan(SHIFT,false,InputOwner::Macro);}
void MacroEngine::WF(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();if(!r.Physical('W')&&!r.Physical('F'))return;if(!r.Physical(VK_SPACE))r.KeyScan(SP,true,InputOwner::Macro);SleepMs(100);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(100);if(!r.Physical(VK_LCONTROL))r.KeyScan(CTRL,true,InputOwner::Macro);for(uint32_t i=0;i<300&&Alive(a,g)&&r.Physical('W');++i){if(!r.Physical(VK_SPACE))r.KeyScan(SP,true,InputOwner::Macro);SleepMs(10);r.KeyScan(SP,false,InputOwner::Macro);count_=i+1;}r.KeyScan(CTRL,false,InputOwner::Macro);}
void MacroEngine::WC(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();for(uint32_t i=0;i<40&&Alive(a,g);++i){r.KeyScan(SP,true,InputOwner::Macro);SleepMs(10);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(10);count_=i+1;}if(Alive(a,g)){r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(100);r.KeyScan(CTRL,false,InputOwner::Macro);SleepMs(20);}}
void MacroEngine::WLAlt(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();r.KeyScan(SP,true,InputOwner::Macro);SleepMs(40);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(230);uint32_t i=0;while(Alive(a,g)&&r.Physical(VK_LMENU)){r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(30);r.KeyScan(CTRL,false,InputOwner::Macro);SleepMs(30);count_=++i;} }
void MacroEngine::SF(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();for(uint32_t i=0;i<50&&Alive(a,g)&&!r.Physical(VK_LBUTTON);++i){r.KeyScan(CTRL,false,InputOwner::Macro);r.KeyScan(SP,true,InputOwner::Macro);SleepMs(30);r.KeyScan(SP,false,InputOwner::Macro);r.KeyScan(SHIFT,true,InputOwner::Macro);SleepMs(30);count_=i+1;}r.KeyScan(SP,false,InputOwner::Macro);r.KeyScan(CTRL,false,InputOwner::Macro);r.KeyScan(SHIFT,false,InputOwner::Macro);}
void MacroEngine::SC(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();r.KeyScan(0x001,true,InputOwner::Macro);SleepMs(30);r.KeyScan(0x001,false,InputOwner::Macro);SleepMs(30);r.KeyScan(0x01F,true,InputOwner::Macro);r.KeyScan(SP,true,InputOwner::Macro);SleepMs(400);r.KeyScan(0x001,true,InputOwner::Macro);SleepMs(30);r.KeyScan(0x001,false,InputOwner::Macro);SleepMs(100);r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(700);r.KeyScan(CTRL,false,InputOwner::Macro);SleepMs(100);r.KeyScan(0x01F,false,InputOwner::Macro);r.KeyScan(SP,false,InputOwner::Macro);}
void MacroEngine::SLAlt(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();r.KeyScan(SP,true,InputOwner::Macro);SleepMs(30);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(30);r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(700);r.KeyScan(CTRL,false,InputOwner::Macro);while(Alive(a,g)&&r.Physical(VK_LMENU)){r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(20);r.KeyScan(CTRL,false,InputOwner::Macro);SleepMs(10);}}
void MacroEngine::ZX(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();r.KeyScan(CTRL,true,InputOwner::Macro);for(uint32_t i=0;i<20&&Alive(a,g);++i){r.KeyScan(0x011,true,InputOwner::Macro);SleepMs(30);r.KeyScan(0x011,false,InputOwner::Macro);SleepMs(60);r.KeyScan(0x01F,true,InputOwner::Macro);SleepMs(30);r.KeyScan(0x01F,false,InputOwner::Macro);SleepMs(60);count_=i+1;}r.KeyScan(CTRL,false,InputOwner::Macro);}
void MacroEngine::ZC(uint32_t a,uint64_t g){auto&r=InputRouter::Instance();r.KeyScan(0x01F,true,InputOwner::Macro);SleepMs(100);r.KeyScan(0x011,true,InputOwner::Macro);for(int j=0;j<3&&Alive(a,g);++j){r.KeyScan(SP,true,InputOwner::Macro);SleepMs(100);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(200);r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(100);r.KeyScan(CTRL,false,InputOwner::Macro);SleepMs(800);}r.KeyScan(0x011,false,InputOwner::Macro);for(uint32_t i=0;i<40&&Alive(a,g);++i){r.KeyScan(SP,true,InputOwner::Macro);SleepMs(10);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(10);count_=i+1;}r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(100);r.KeyScan(CTRL,false,InputOwner::Macro);r.KeyScan(SP,true,InputOwner::Macro);SleepMs(10);r.KeyScan(SP,false,InputOwner::Macro);r.KeyScan(0x01F,false,InputOwner::Macro);}
void MacroEngine::Turn(uint32_t a,uint64_t g,bool right){auto&r=InputRouter::Instance();r.KeyScan(0x01F,true,InputOwner::Macro);SleepMs(180);r.KeyScan(SP,true,InputOwner::Macro);SleepMs(30);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(30);r.MouseMove(right?400:-400,0);r.KeyScan(right?0x01E:0x020,true,InputOwner::Macro);r.KeyScan(CTRL,true,InputOwner::Macro);SleepMs(r.Physical(VK_LBUTTON)?240:540);r.KeyScan(SP,true,InputOwner::Macro);SleepMs(30);r.KeyScan(SP,false,InputOwner::Macro);SleepMs(30);r.MouseMove(right?-400:400,0);SleepMs(r.Physical(VK_LBUTTON)?400:880);r.KeyScan(right?0x01E:0x020,false,InputOwner::Macro);while(Alive(a,g)&&r.Physical('S'))SleepMs(10);r.KeyScan(0x01F,false,InputOwner::Macro);r.KeyScan(CTRL,false,InputOwner::Macro);}
void MacroEngine::TurnLeft(uint32_t a,uint64_t g){Turn(a,g,false);} void MacroEngine::TurnRight(uint32_t a,uint64_t g){Turn(a,g,true);}
}
